<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>QR Code Generator</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #f4f4f4;
            color: #333;
            margin: 0;
            padding: 0;
            text-align: center;
        }

        header {
            background-color: #4CAF50;
            padding: 20px 0;
            color: white;
        }

        form {
            margin-top: 20px;
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        input[type="text"] {
            padding: 10px;
            margin-bottom: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            width: 300px;
            font-size: 16px;
        }

        button {
            background-color: #4CAF50;
            color: white;
            padding: 10px 20px;
            font-size: 16px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }

        button:hover {
            background-color: #45a049;
        }

        img {
            margin-top: 20px;
            max-width: 100%;
        }

        #history {
            margin-top: 50px;
            text-align: left;
            max-width: 600px;
            margin-left: auto;
            margin-right: auto;
        }

        #history h2 {
            color: #333;
            font-size: 24px;
            margin-bottom: 10px;
        }

        #history ul {
            list-style-type: none;
            padding: 0;
            margin: 0;
        }

        #history li {
            margin-bottom: 20px;
        }

        #history li img {
            max-width: 100%;
        }

        .warning {
            color: red;
            margin-top: 10px;
        }
    </style>
</head>
<body>
    <header>
        <h1>QR Code Generator</h1>
    </header>

    {% if warning %}
        <p class="warning">{{ warning }}</p>
    {% endif %}

    <form action="/generate_qr" method="post">
        <input type="text" name="text_entry" placeholder="Enter data" required>
        <br>
        <button type="submit">Generate QR Code</button>
    </form>

    {% if qr_image %}
        <img src="data:image/png;base64,{{ qr_image }}" alt="QR Code">
    {% endif %}

    <!-- History Section -->
    <div id="history">
        <h2>History</h2>
        <ul>
            {% for entry in history %}
                <li>
                    <p><strong>Typed Data:</strong> {{ entry.data }}</p>
                    <img src="data:image/png;base64,{{ entry.qr_image }}" alt="QR Code">
                </li>
            {% endfor %}
        </ul>
    </div>
</body>
</html>
